apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask-app
          image: manusm123/flask-app:latest  # Your Docker Hub username is correctly added
          ports:
            - containerPort: 5000
          imagePullPolicy: Always  # Ensures the latest image is pulled
