apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 80          # External port exposed by the service
      targetPort: 5000  # The port your Flask app is running on inside the container
      nodePort: 31369   # Manually defining a NodePort (optional, must be between 30000-32767)
  type: NodePort
